// import './oop/class'
// import './designPrinciple/example/promise'
// import '../case/case1'
// import '../case/case2'
// import './designPattern/creational/factoryPattern'
// import './designPattern/creational/singletonPattern'
// import './designPattern/creational/singletonPattern/demo/simulateLogin'
// import './designPattern/structural/adapterPattern'
// import './designPattern/structural/decoratorPattern'
// import './designPattern/structural/decoratorPattern/demo/decorationClass'
// import './designPattern/structural/decoratorPattern/demo/decorationClassWithArgs'
// import './designPattern/structural/decoratorPattern/demo/decorationClassByMixin'
// import './designPattern/structural/decoratorPattern/demo/decorationMethod'
import './designPattern/structural/decoratorPattern/demo/core-decorators'
