// import './oop/class'
// import './designPrinciple/example/promise'
// import '../case/case1'
// import '../case/case2'
// import './designPattern/creational/factoryPattern'
// import './designPattern/creational/singletonPattern'
// import './designPattern/creational/singletonPattern/demo/simulateLogin'
// import './designPattern/structural/adapterPattern'
import './designPattern/structural/decoratorPattern'
